name: CI
on:
  push:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Test
        run: cargo test --verbose --workspace

      - name: Clippy
        run: cargo clippy --verbose --workspace -- -D warnings

      - name: Audit
        run: cargo audit

  compile:
    name: Compile ${{ matrix.target }}
    runs-on: ${{ matrix.runs_on && matrix.runs_on || 'ubuntu-latest'  }}
    if: github.event_name == 'push'
    needs: check
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            executable_path: target/{target}/release/bud.exe
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz
            executable_path: target/{target}/release/bud
          - target: x86_64-apple-darwin
            archive: zip
            executable_path: target/release/bud
            runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install podman
        if: matrix.target != 'x86_64-apple-darwin'
        run: |
          sudo apt-get -y upgrade
          sudo apt-get -y install podman

      - name: Install cross
        if: matrix.target != 'x86_64-apple-darwin'
        run: cargo install cross

      - name: Add target
        if: matrix.target != 'x86_64-apple-darwin'
        run: rustup target add ${{ matrix.target }}

      - name: Compile
        if: matrix.target != 'x86_64-apple-darwin'
        run: cross build --release --workspace --target=${{ matrix.target }}

      - name: Compile
        if: matrix.target == 'x86_64-apple-darwin'
        run: cargo build --release --workspace

      - name: Executable path
        id: vars
        run: |
          executable_path=${{ matrix.executable_path }}
          executable_path=${executable_path/\{target\}/${{ matrix.target }}}
          echo "executable_path=$executable_path" > $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            ${{ steps.vars.outputs.executable_path }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: compile
    if: github.event_name == 'push'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Zip
        run: |
          zip -r x86_64-pc-windows-gnu.zip artifacts/x86_64-pc-windows-gnu
          zip -r x86_64-apple-darwin.zip artifacts/x86_64-apple-darwin
          tar -czf x86_64-unknown-linux-gnu.tar.gz artifacts/x86_64-unknown-linux-gnu

      - uses: dev-drprasad/delete-tag-and-release@085c6969f18bad0de1b9f3fe6692a3cd01f64fe5
        with:
          delete_release: true
          tag_name: nightly
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Create the release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: Nightly Build ${{ steps.vars.outputs.sha_short }}
          draft: false
          prerelease: false
          files: |
            x86_64-pc-windows-gnu.zip
            x86_64-apple-darwin.zip
            x86_64-unknown-linux-musl.tar.gz
